{% set name = "xdsmjs" %}
{% set version = "1.0.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xdsmjs-{{ version }}.tar.gz
  sha256: 982411616e7cfd8ac703fd0af7369bf7c01269d69db2dbbcd65672d227e65e8e

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - xdsmjs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OneraHub/XDSMjs
  summary: XDSMjs Python module
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AntoineD
