{% set name = "xdsmjs" %}
{% set version = "2.0.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/xdsmjs-{{ version }}.tar.gz
  sha256: 314183dbcf66ab13af1262158a0e45467146ee56856013a8225bf1c0b447562a

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=2.7
  run:
    - python >=2.7

test:
  imports:
    - xdsmjs
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/OneraHub/XDSMjs
  summary: XDSMjs Python module
  license: Apache-2.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - AntoineD
